version: '2'

services:
  php:
    container_name: liguehb-php
    hostname: liguehb-php
    build: .
    restart: "unless-stopped"
    ports:
      - 8090:80
    volumes:
      - ./web:/var/www/html

